export const navItems = [
  { path: '/', icon: 'LayoutDashboard', label: 'Dashboard' },
  { path: '/add', icon: 'Plus', label: 'Add' },
  { path: '/transactions', icon: 'List', label: 'Transactions' },
  { path: '/goals', icon: 'Target', label: 'Goals' },
  { path: '/roadmap', icon: 'Map', label: 'Roadmap' },
  { path: '/recurring', icon: 'Repeat', label: 'Recurring' },
  { path: '/savings', icon: 'Building2', label: 'Savings' },
  { path: '/debts', icon: 'TrendingDown', label: 'Debts' },
  { path: '/trends', icon: 'TrendingUp', label: 'Trends' },
  { path: '/review', icon: 'Calendar', label: 'Review' },
  { path: '/year-review', icon: 'Trophy', label: 'Year' },
  { path: '/credit-score', icon: 'CreditCard', label: 'Credit' },
  { path: '/settings', icon: 'Settings', label: 'Settings' },
  { path: '/account', icon: 'User', label: 'Account' },
]
