import {
  LayoutDashboard,
  Plus,
  List,
  Target,
  Map,
  Repeat,
  Building2,
  TrendingDown,
  TrendingUp,
  Calendar,
  Trophy,
  CreditCard,
  Settings,
  User,
  Cloud,
  Lock,
  Home,
  Lightbulb,
  ShoppingCart,
  Car,
  Shield,
  HeartPulse,
  UtensilsCrossed,
  Film,
  ShoppingBag,
  Smartphone,
  Plane,
  Palette,
  Wallet,
  GraduationCap,
  LifeBuoy,
  Banknote,
  Laptop,
  Wrench,
  BarChart3,
  Landmark,
  Gift,
  DollarSign,
  Hand,
  Leaf,
  Package,
  Music,
  Baby,
  Dog,
  Pause,
  Play,
  FileText,
  Check,
  AlertTriangle,
  ArrowUpRight,
  ArrowDownRight,
  Copy,
  Pencil,
  BookOpen,
  ExternalLink,
  ChevronRight,
  HardDrive,
  RefreshCw,
  WifiOff,
  Key,
  type LucideIcon,
} from 'lucide-react'

/** Maps icon name (stored in DB or used in code) to Lucide component */
const ICON_MAP: Record<string, LucideIcon> = {
  LayoutDashboard,
  Plus,
  List,
  Target,
  Map,
  Repeat,
  Building2,
  TrendingDown,
  TrendingUp,
  Calendar,
  Trophy,
  CreditCard,
  Settings,
  User,
  Cloud,
  Lock,
  Home,
  Lightbulb,
  ShoppingCart,
  Car,
  Shield,
  HeartPulse,
  UtensilsCrossed,
  Film,
  ShoppingBag,
  Smartphone,
  Plane,
  Palette,
  Wallet,
  GraduationCap,
  LifeBuoy,
  Banknote,
  Laptop,
  Wrench,
  BarChart3,
  Landmark,
  Gift,
  DollarSign,
  Hand,
  Leaf,
  Package,
  Music,
  Baby,
  Dog,
  Pause,
  Play,
  FileText,
  Check,
  AlertTriangle,
  ArrowUpRight,
  ArrowDownRight,
  Copy,
  Pencil,
  BookOpen,
  ExternalLink,
  ChevronRight,
  HardDrive,
  RefreshCw,
  WifiOff,
  Key,
}

/** Legacy emoji -> Lucide icon name for backward compatibility */
const EMOJI_TO_ICON: Record<string, string> = {
  '🏠': 'Home',
  '💡': 'Lightbulb',
  '🛒': 'ShoppingCart',
  '🚗': 'Car',
  '🛡️': 'Shield',
  '🏥': 'HeartPulse',
  '🍽️': 'UtensilsCrossed',
  '🎬': 'Film',
  '🛍️': 'ShoppingBag',
  '📱': 'Smartphone',
  '✈️': 'Plane',
  '🎨': 'Palette',
  '💰': 'Wallet',
  '🏦': 'Building2',
  '📈': 'TrendingUp',
  '🆘': 'LifeBuoy',
  '📚': 'GraduationCap',
  '💳': 'CreditCard',
  '💵': 'Banknote',
  '💻': 'Laptop',
  '🛠️': 'Wrench',
  '📊': 'BarChart3',
  '🏛️': 'Landmark',
  '🎁': 'Gift',
  '💲': 'DollarSign',
  '👋': 'Hand',
  '💚': 'Leaf',
  '🎯': 'Target',
  '🔄': 'Repeat',
  '📋': 'List',
  '🗺️': 'Map',
  '🗓️': 'Calendar',
  '🏆': 'Trophy',
  '⚙️': 'Settings',
  '👤': 'User',
  '☁️': 'Cloud',
  '🔐': 'Lock',
  '➕': 'Plus',
  '📉': 'TrendingDown',
  '🏖️': 'Plane',
  '💍': 'Gift',
  '🎓': 'GraduationCap',
  '🎮': 'Package',
  '👶': 'Baby',
  '🐕': 'Dog',
  '🪙': 'DollarSign',
  '🧾': 'List',
  '🔧': 'Wrench',
}

function resolveIconName(nameOrEmoji: string): string {
  const trimmed = String(nameOrEmoji ?? '').trim()
  if (!trimmed) return 'Wallet'
  if (EMOJI_TO_ICON[trimmed]) return EMOJI_TO_ICON[trimmed]
  if (ICON_MAP[trimmed]) return trimmed
  return 'Wallet'
}

export interface IconProps {
  name: string
  className?: string
  size?: number
}

export function Icon({ name, className = '', size = 20 }: IconProps) {
  const resolved = resolveIconName(name)
  const Component = ICON_MAP[resolved] ?? Wallet
  return <Component className={className} size={size} strokeWidth={1.75} aria-hidden />
}

/** Icon names for debt picker */
export const DEBT_ICONS = [
  'CreditCard',
  'Home',
  'Car',
  'GraduationCap',
  'HeartPulse',
  'Smartphone',
  'TrendingDown',
  'Wallet',
  'Building2',
] as const

/** Icon names for savings goal picker */
export const GOAL_ICONS = [
  'Plane',
  'Car',
  'Home',
  'Gift',
  'GraduationCap',
  'Smartphone',
  'Package',
  'Plane',
  'Baby',
  'Dog',
  'Wallet',
  'Target',
] as const

/** Icon names for savings account picker */
export const ACCOUNT_ICONS = [
  'Building2',
  'CreditCard',
  'Wallet',
  'BarChart3',
  'Banknote',
  'DollarSign',
  'TrendingUp',
  'Shield',
] as const

/** Icon names for category picker and seed data */
export const CATEGORY_ICONS = [
  'Wallet',
  'Banknote',
  'CreditCard',
  'Home',
  'Car',
  'ShoppingCart',
  'Lightbulb',
  'HeartPulse',
  'Shield',
  'UtensilsCrossed',
  'Film',
  'ShoppingBag',
  'Smartphone',
  'Plane',
  'Palette',
  'TrendingUp',
  'Building2',
  'GraduationCap',
  'Laptop',
  'Wrench',
  'BarChart3',
  'Landmark',
  'Gift',
  'DollarSign',
  'Package',
  'Dog',
  'Baby',
  'Music',
  'List',
] as const
